<!DOCTYPE html>
<html>

	<head>
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta charset="UTF-8">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
		<title>发布规则</title>
		<link rel="shortcut icon" href="clientapp/images/new_images/favicon.ico" />
		<link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css" />
		<link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css" />
		<link href="/static/home/mobile/css/new_style.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="/static/home/mobile/js/jquery.min.js"></script>
	</head>
	<style type="text/css">
		* {
			margin: 0px;
			padding: 0px;
		}
		
		html {
			font-size: 62.5%;
		}
		
		body {
			font-family: "微软雅黑", "Microsoft Yahei", "Arial";
			font-size: 1.4rem;
			background: #F5F5F5;
			line-height: 1.5;
			color: #333;
			overflow-x: hidden;
			overflow-y: auto;
			-webkit-overflow-scrolling: touch;
		}
		
		a {
			text-decoration: none;
			-webkit-transition: all 0.3s ease-in-out;
			transition: all 0.3s ease-in-out;
			color: #333;
		}
		.help-cont{
			width: 96%;
			margin: 60px 2% 0;
		}
		.help-cont ul{
			overflow: hidden;
		}
		.help-cont ul li{
			width: 46%;
			margin: 10px 2%;
			float: left;
			border-radius: 3px;
			line-height: 30px;
			text-align: center;
			color: #fff;
			background-color: #F58D1F;
		}
		.help-cont ul li.active{
			background-color: #FE4B1C;
		}
		.help-cont-box .item{
			display: none;
			text-align: center;
		}
		.help-cont-box .item h2{
			text-align: left;
		}
		.help-cont-box .item img{
			width: 70%;
			max-width: 377px;
			margin: 0 auto 20px;
		}
		.help-cont-box .item.active{
			display: block;
		}

		.content{
			padding-top: 80px;
			padding-left: 15px;
			padding-right: 15px;
			padding-bottom: 15px;
		}
	</style>
	<body>
		<div class="site-header header-fixed">
			<a onclick="window.history.back();" class="back"></a>
			<div class="tit-name">发布规则</div>
		</div>
		<div class="content">
		    《发布规则》
<br/>为了创造一个良好、和谐、诚信的交易环境，现 制定请大家主动遵守发布规则。
<br/>    1. 不得发布法律法规所禁止的内容任务；
<br/>    2. 禁止语言粗暴带脏话及歧视诅咒类语言；
<br/>    3. 不得发布与本平台提供服务高度相似的任务；
<br/>    4. 禁止向外拉人行为，在平台发布任务，而让接 单者加微信或进群另行发红包或做任务的，一经 发现永久封。
<br/>    5. 严禁任务造假，发布不可能完成的任务，或通 过率极低的，完成任务周期需要较长的，任务中 又没有明确提示的，都将按伪任务处理；
<br/>    6. 任务中需要接单者另外付出成本高于所获佣 金，且任务中没有明确说明的，如遇申诉将直接 按接单合格处理，明显有诱导欺骗行为的，冻结任务，严重者封号；
<br/>    7. 不按类别发布任务、驳回任务不写原因、语 言粗暴带脏话的，如遇申诉，直接按接单合格处 理；
<br/>    8. 当遇到任务申诉，平台将尽最大努力秉承公正 裁决，但不能保证每次裁决均为客观正确。尤其 需要凭商家后台数据作为审核标准的任务，因无 法查阅贵平台数据，只能根据截图本身是否符合 任务做出裁定，敬请知晓；
<br/>    9. 如遇骗单，用假图、ps图冒充验证图行为，请 保留证据及时向平台举报；
<br/>    10. 任务价格设定合理，乐推平台均为自然人，非机器亦非刷手，几毛钱的任务又让注册又 绑定的，就请不要再抱怨无人接单了，互利才可 成交生意，抱着占便宜的目的就请不要发单了；
<br/>    11. 发布任务时，要求接单者必须完成的数据， 如金额、数量等，必须写在备注或操作说明里， 须表达清晰明确，不可以含混，验证图上的相关 数据不作为任务是否完成的判断标准；验证图与 实际任务不符、用个人微信二维码替代公众号二 维码或下载链接、伪造任务链接、伪造二维码等 一切采用蒙骗手段企图骗取审核过关的，一经发现，立即冻结任务，余额不退，严重者封号处理；
<br/>12.系统规则：
<br/>1）	任务发布后支持修改，每个任务每日可修改1 次；任务支持刷新，刷新会使任务排名靠前，刷 新次数详见会员等级权益；
<br/>2）	任务可以随时暂停随时开启；
<br/>3）	进行中的任务可以增加数量和价格，仅限上
<br/>调；
<br/>4）	任务发布后可以提前下架，仅限进行中为。且无 申诉情况时可以进行该操作，请注意提示谨慎操 作；
<br/>5）	任务下架后系统自动清算；
<br/>6）	并行接单数量限制5个，接单任务被驳回，接单 者在12小时内可以选择重做任务重新提交或发起 申诉，超过12小时不做任何处理任务自动释放；
<br/>7）	终审不合格任务会直接释放，可以重新抢单；
<br/>8）	任务结束不影响任务审核；
<br/>9）	验证图24小时内未审核，系统会默认合格。任 务发生被申诉情况，悬赏主需要在24小时内进行 处理，否则直接判定申诉成立；
<br/>10）	发布任务收取一定的服务费，根据会员的等级
<br/>不同收费比例不同，详情请见发布任务页面或会 员申请页面；
<br/>11 ）充值提现时间为工作日的 9:00-17:00,提现收取一定费率的手续 费，平台会在3个工作 日内审核，如无违规行为，审核通过后会自动发 放。
<br/>12）	长单任务因可以自定义接单及审核时间，不受 以上系统时间限制，另需特别注意，长单任务不 能暂停不能提前下架，请综合决策后再发布。接 单限时不能超过审核限时，如接单限时超过审核 限时，任务到期清算后进行中的任务将被自动默 认为合格，任务截止时间不得小于审核限时，如 小于任务将不予审核通过！
<br/>13）	平台任务采取预审制，审核时间为 9:00-23:00 o如采取欺瞒掩饰等手段蒙混通过审 核，被用户举报或被平台巡查发现，任务将被冻 结，余额不退，严重者封号处理。特别声明，平 台对任务的审核只是基础性的是否符合本平台发 布规则的审核，不对任务内容本身运营风险作出 任何判断，任务本身的经营或其它潜在风险不在
<br/>平台审核范围之内，任务发布者需对自己发布的 任务承担全部责任，需对自己发布的任务风险有 充分的评估和具有相应的风险承受能力，如任务 中途出现问题无法运营或跑路等给接单者造成损 失的，平台将依规冻结任务及扣除相应保证金， 您如果也遭受到了损失，请您与您的任务商家协 商解决，本平台不负责处理。您需要知晓此规 则，否则请不要发布任务，一旦发布将视为您同 意遵守本规则！
<br/>14）	任务结束后数据保留30天，超过30天系统自 动清除，需要保留图片等相关数据的请提前备 份。
<br/>15）	存在交易风险的任务需缴纳保证金方可发 布，一，保证金缴纳金额大于任务总额，不 足100元的按100元缴纳。
<br/>16）	推荐或置顶规则
<br/>    a. 推荐或置顶成功后未到期前可以续期，时间自 动累加；
<br/>    b. 推荐或置顶只针对本任务有效，任务不能中途
<br/>更换；
<br/>C.任务中途暂停，推荐或置顶时间不会暂停；
<br/>    d. 提前下架或置顶未到期任务提前完成，剩余推 荐或置顶时间不会保留也不会折算成任务币返 还；
<br/>    e, 推荐及置顶都是收费项目，请充分评估商业价 值后再使用，推荐或置顶成功后不能退改。
<br/>17）会员开通后不做退费处理，请您谨慎选择。
<br/>购买同等级会员可续期，时间累加；若购买会员 未到期，再次开通不同等级，则以最近一次购买 等级为准，时间重新计算，请考虑成熟后再行购 买；
<br/>13.保证金处罚条例：
<br/>1）	发布的任务如存在私下交易、私下发布其他任 务、恶意篡改任务链接、二维码等，但任务内容 不存在违规违法行为，视投诉情况及任务单价范 围，将处以200~500元之间的罚款，罚款直接从 保证金中扣除；
<br/>2）	通过加粉或通过平台渠道联系到用户，私下 进行推广违规任务，如：推广同类平台、赌博 类、涉黄类、挂机软件类、投资类等造成大量投 诉但并未给用户造成严重的经济损失，将处以100-1000元之间的罚款，罚款直接从保证金中 扣除；
<br/>3）	通过发布加粉类、投资理财类、投票类、关注 类等任务聚集用户，私下实施诈骗或发布违法任 务，将罚没全部保证金，并永久冻结账户；
<br/>4）	冒充平台工作人员，收取会费或私下以本平台 名义发布任务的，将罚没全部保证金，并永久冻 结账户；
<br/>5）	态度恶劣，不能主动承认错误、找各种借口和 理由拒不悔改、辱骂、威胁平台及工作人员的将 从重加倍处罚；
<br/>6）	以上违规情节严重的，将交由公安机关处理。
<br/>14,发布的任务中禁止添加微信或QQ等联系方 式，对于必须要通过加微信或QQ才能完成的任 务或有需要和用户进行沟通的任务，在缴纳保证 金（不低于1000元）后可以添加，如采用欺骗手 段蒙混过审，产生私下交易或纠纷，一经发现， 将立即冻结该任务，余额不退，并扣除全部保证 金，严重者封号处理。
<br/>如有违规根据情节将给予警告、冻结任务及封号 等处理，冻结任务及封号余额不退。您需要知晓 并遵循以上原则和要求，如不愿意接受，请勿发 布任务，一旦发布将视为您同意實守本规则。
<br/>注：本规则会根据业务发展的需要适时作出调整 和修改，最终解释权归乐推所有。
	</div>
        <script type="text/javascript">
            $(function () {
                $('.navs li').click(function () {
                    var obj = $('.navs li');
                    var index = obj.index(this);
                    obj.removeClass('active').eq(index).addClass('active');
                    $('.item').removeClass('active').eq(index).addClass('active');
                });
            });
        </script>
    </body>
</html>