<html>

<head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>找回密码</title>
    <link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css" />
    <link href="/static/home/mobile/css/style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/home/mobile/css/new_style.css" />
    <script type="text/javascript" src="/static/home/mobile/js/jquery.min.js"></script>
    <!-- 弹出层 -->
    <link rel="stylesheet" href="/static/plugins/dialog/css/dialog.css" />
    <script src="/static/plugins/dialog/lib/zepto.min.js"></script>
    <script src="/static/plugins/dialog/js/dialog.js"></script>
    <!-- 弹出层 -->
    <script type="text/javascript" src="/static/home/mobile/js/global.js"></script>
</head>

<body>
    <style>
        .site-header .tit-name {
            overflow: initial;
        }

        #tomial {
            width: 100%;
            height: 30px;
            color: #fff;
            font-size: 14px;
            background-color: #FE4B1C;
            pointer-events: initial;
            border: none;
            border-radius: 3px;
            outline: none;
            -webkit-appearance: none;
        }
    </style>
    <div class="find-pwd">
        <div class="site-header">
            <a onclick="window.history.back();" class="back"></a>
            <div class="tit-name">忘记密码</div>
        </div>
        <div class="main findPwd">
            <div class="denglu-box">
                <div class="dl-form">
                    <form id="formForgetpass">
                        <div class="item-box">
                            <input name="username" id="forgetpass-username" placeholder="请输入注册的手机号" type="text" class="m_txt">
                        </div>
                        <div class="item-box">
                            <input type="password" name="password" class="m_txt" placeholder="输入新密码" id="forgetpass-password">
                        </div>
                        <div class="item-box">
                            <input type="password" name="password_confirm" class="m_txt" placeholder="重复新密码" id="forgetpass-confirm-password">
                        </div>

                        <div class="item-box">
                            <input type="text" class="m_txt" placeholder="输入验证码" name="captcha" id="forgetpass-verifycode" />
                            <div class="yzm">
                                <img id="forgetpass-verifycodeimg" style="width:90px; height:30px;" src="{:captcha_src()}" onclick="this.src='{:captcha_src()}?'+Math.random()" alt="captcha" />
                            </div>
                        </div>
                        <div class="item-box">
                            <input id="verification" name="verification" class="button1 active m_txt" placeholder="请输入短信验证码" required />
                            <div class="yzm">
                                <button type="button" id="tomial" class="btn btn-primary text-center">发送验证码</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
            <div style="padding: 10px;color:red;font-size: 14px; line-height: 22px;">
                <label id="okForgetpass" style="display: none;">请前往您的邮箱查收找回密码邮件，<br />并通过链接重置新的登录密码！</label>
            </div>
        </div>
        <div class="member-btn">
            <input type="button" class="button1" value="确认修改" id="ajax-forgetpass" />
        </div>
    </div>

    <script type="text/javascript">
        $(function() {
            var $okbox = $("#okForgetpass");
            var $form = $("#formForgetpass");
            var $username = $("#forgetpass-username");
            var $email = $("#forgetpass-email");
            var $verifycode = $('#forgetpass-verifycode');
            var $submit = $("#ajax-forgetpass");
            var $password = $('#forgetpass-password');
            var $confirm_password = $('#forgetpass-confirm-password');
            var $verification = $('#verification');

            function validateEmail(email) {
                var error = 0;
                var reg = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;
                if (email.length == 0) {
                    error = 1;
                    $email.addClass("error");
                    message("请输入邮箱地址", "", "error");
                } else if (!reg.test(email)) {
                    error = 1;
                    $email.addClass("error");
                    message("请输入正确的邮箱地址", "", "error");
                }
                return error;
            }

            function verifycodeimg(prefix) {
                var timenow = new Date().getTime();
                $('#' + prefix + '-verifycodeimg').attr("src", '{:captcha_src()}?' + timenow);
            }

            $email.change(function() {
                verifycodeimg('forgetpass');
            });

            // $email.blur(function() {
            //     var username = $username.val();
            //     if ($.trim(username) == "") {
            //         message("用户名不能为空", "", "error");
            //         return false;
            //     }

            //     var email = $email.val();
            //     var error = validateEmail(email);
            //     if (error != 0)
            //         return false;

            //     var server = "/home/forgetpass/checkemail";
            //     var data = {
            //         "username": $username.val(),
            //         "email": $email.val()
            //     };
            //     Common.ApiPost(server, data, function(res) {
            //         if (res.type != "success") {
            //             $email.addClass("error");
            //             message(res.message, '', res.type);
            //         } else {
            //             $email.removeClass("error");
            //         }
            //     });
            // });

            $('#tomial').click(function() {
                var mobile = $username.val();
                var partten = /^1[3-9]\d{9}$/;

                if (!partten.test(mobile)) {
                    message('请输入正确的手机号', '', 'error');
                    return false;
                }

                var validate = $verifycode.val();
                if (validate == '') {
                    message('请输入验证码', '', 'error');
                    return false;
                }

                $("#tomial").attr("disabled", true);

                var data = {
                    type: 2,
                    mobile: mobile,
                    validate: validate
                };
                Common.ApiPost("/home/register/sendsmscode", data, function(res) {
                    if (res.type != "success") {
                        $('.yzm img').click();
                        $("#tomial").attr("disabled", false);
                        message(res.message, res.redirect, res.type);
                        return;
                    }
                    new invokeSettime("#tomial");
                }, function(res) {
                    $('.yzm img').click();
                    $("#tomial").attr("disabled", false);
                    message(res.message, res.redirect, res.type);
                });
            });

            $submit.click(function() {
                var username = $username.val();
                var password = $password.val();
                var confirm_password = $confirm_password.val();
                var verification = $verification.val();
                var password_empty = "新密码不能为空。";
                var password_shorter = "新密码不能少于 6 个字符。";
                var confirm_password_invalid = "两次输入新密码不一致";
                var passwd_balnk = "密码中不能包含空格";
                var verifycode_required = "请输入验证码";
                var verifycode_faild = '验证码输入错误';
                if ($.trim(username) == "") {
                    message("用户名不能为空", "", "error");
                    return false;
                }

                // var email = $email.val();
                var verifycode = $verifycode.val();
                // var error = validateEmail(email);
                // if (error != 0)
                //     return false;

                if (password.length == 0) {
                    error = 1;
                    $password.addClass("error");
                    message(password_empty, "", "error");
                    return;
                } else if (password.length < 6) {
                    error = 1;
                    $password.addClass("error");
                    message(password_shorter, "", "error");
                    return;
                } else if (/ /.test(password) == true) {
                    error = 1;
                    $password.addClass("error");
                    message(passwd_balnk, "", "error");
                    return;
                } else if (confirm_password.length == 0) {
                    error = 1;
                    $confirm_password.addClass("error");
                    message("请输入确认密码", "", "error");
                    return;
                } else if (confirm_password != password) {
                    error = 1;
                    $confirm_password.addClass("error");
                    message(confirm_password_invalid, "", "error");
                    return;
                } else if (verifycode.length < 4) {
                    error = 1;
                    $verifycode.addClass("error");
                    message(verifycode_required, "", "error");
                    return;
                }

                // var server = "/home/forgetpass/sendmail";
                var server = "/home/forgetpass/forgetpassword";
                var data = {
                    "username": $username.val(),
                    "password": password,
                    "confirm_password": confirm_password,
                    "captcha": verifycode,
                    "verification": verification
                };
                Common.ApiPost(server, data, function(res) {
                    if (res.redirect == -1) {
                        message("会员信息不存在或被禁止登录", "", "error");
                        return;
                    } else if (res.redirect == -2) {
                        $verifycode.addClass("error");
                        message(verifycode_faild, "", "error");
                        return;
                    }

                    if (res.type == 'error') {
                        message(res.message, '', 'error');
                        return;
                    }

                    if (res.redirect != 0) {
                        verifycodeimg();
                    } else {
                        $password.removeClass("error");
                        $confirm_password.removeClass("error");
                        $verifycode.removeClass("error");

                        window.location = '/home/auth/login.html';
                    }
                });
            });
        });

        function invokeSettime(obj) {
            var countdown = 60;
            settime(obj);

            function settime(obj) {
                if (countdown == 0) {
                    $(obj).attr("disabled", false);
                    $(obj).text("获取验证码");
                    countdown = 60;
                    return;
                } else {
                    $(obj).attr("disabled", true);
                    $(obj).text("(" + countdown + ") s 重发");
                    countdown--;
                }
                setTimeout(function() {
                    settime(obj)
                }, 1000)
            }
        }
    </script>
</body>

</html>